parameters:
#    walva_user.example.class: Walva\UserBundle\Example

services:
#    walva_user.example:
#        class: %walva_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
