walva_supportkot:
    resource: "@WalvaNatagoraBundle/Resources/config/routing.yml"
    prefix:   /
    
natagora_formation:
  resource:  "@WalvaNatagoraBundle/Resources/config/routing/formation.yml"
  prefix:   /formation
  