walva_user:
    resource: "@WalvaUserBundle/Resources/config/routing.yml"
    prefix:   /

walva_natagora:
    resource: "@WalvaNatagoraBundle/Resources/config/routing.yml"
    prefix:   /
    
index:
    pattern:  /
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:index" }


login:
    pattern:   /login
    defaults:  { _controller: WalvaUserBundle:Security:login }
 
login_check:
    pattern:   /login_check
 
logout:
    pattern:   /logout