evenement:
    pattern:  /
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:index" }

evenement_sort:
    pattern:  /sortBy/{sort}
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:index" }

evenement_sort_with_order:
    pattern:  /sortBy/{sort}/{order}
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:index" }

deleted_evenement:
    pattern:  /deleted
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:listDeletedEntities" }

deleted_evenement_sort:
    pattern:  /deleted/sortBy/{sort}
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:listDeletedEntities" }

deleted_evenement_sort_with_order:
    pattern:  /deleted/sortBy/{sort}/{order}
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:listDeletedEntities" }

evenement_show:
    pattern:  /{id}/show
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:show" }

evenement_new:
    pattern:  /new
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:new" }

evenement_create:
    pattern:  /create
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:create" }
    requirements: { _method: post }

evenement_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:edit" }

evenement_update:
    pattern:  /{id}/update
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:update" }
    requirements: { _method: post|put }

evenement_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "WalvaNatagoraBundle:Evenement:delete" }
    requirements: { _method: post|delete }

