inscription_evenement:
    pattern:  /inscription/evenement/{evenement}/eleve/{eleve}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:inscrire" }

desinscription_evenement:
    pattern:  /desinscription/evenement/{evenement}/eleve/{eleve}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:desinscrire" }

inscription_refresh:
    pattern:  /refresh/evenement/{evenement}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:refresh" }

