inscription_evenement:
    pattern:  /inscription/evenement/{evenement}/eleve/{eleve}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:inscrire" }

desinscription_evenement:
    pattern:  /desinscription/evenement/{evenement}/eleve/{eleve}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:desinscrire" }

inscription_refresh:
    pattern:  /refresh/evenement/{evenement}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:refresh" }

invite_create:
    pattern:  /invite/create/{evenement}/{eleve}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:createInvite" }
    requirements: { _method: post }

invite_new:
    pattern:  /invite/new/{evenement}/{eleve}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:newInvite" }

invite_cancel:
    pattern:  /invite/cancel/{invite}
    defaults: { _controller: "WalvaNatagoraBundle:Inscription:cancelInvite" }
