natagora_formation:
    resource: "@WalvaNatagoraBundle/Resources/config/routing/formation.yml"
    prefix:   /admin/formation

natagora_lieu:
        resource: "@WalvaNatagoraBundle/Resources/config/routing/lieu.yml"
        prefix:   /admin/lieu
        
natagora_formateur:
        resource: "@WalvaNatagoraBundle/Resources/config/routing/formateur.yml"
        prefix:   /admin/formateur

natagora_evenement:
        resource: "@WalvaNatagoraBundle/Resources/config/routing/evenement.yml"
        prefix:   /admin/evenement
        