walva_natagora_formation:
    resource: "@WalvaNatagoraBundle/Resources/config/routing/formation.yml"
    prefix:   /formation

WalvaNatagoraBundle_lieu:
        resource: "@WalvaNatagoraBundle/Resources/config/routing/lieu.yml"
        prefix:   /lieu
        
WalvaNatagoraBundle_formateur:
        resource: "@WalvaNatagoraBundle/Resources/config/routing/formateur.yml"
        prefix:   /formateur
